runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /server-build\.js
  static_files: app/server-build.js
  upload: app/server-build\.js$
  application_readable: true
  login: admin
  secure: always

- url: /(.+(\.js|\.css|\.png|\.map))$
  static_files: app/\1
  upload: app/(.+(\.js|\.css|\.png|\.map))$
  expiration: 10m
  secure: always

- url: /.*
  script: _go_app
  secure: always
