runtime: go
api_version: go1.8

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /(.+(\.html|\.js|\.css))$
  static_files: app/\1
  upload: app/(.+(\.html|\.js|\.css))$
  expiration: 10m
  secure: always

- url: /(.+\.(ico|txt|mp3))$
  static_files: app/\1
  upload: app/(.+\.(ico|txt|mp3))$
  secure: always

- url: /.*
  script: _go_app
  secure: always
